### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by maullerz** [maullerz/react-formal-examples#1]
TODO:
- [ ] react-bootstrap
- [x] deploy to heroku || github-pages
- [ ] auth forms - Login + Registration
- [ ] account form - get/update
- [ ] Complex form
- [ ] custom simple controls like dropdown, switch, datepicker
- [ ] custom complex control - array of objects, e.g "contacts[1].fullname"

https://github.com/jquense/react-formal/issues/92
